'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.18444
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("ItemTag.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Duplicate Tag Found - Would you like the next available sequence number to be generated for you?.
        '''</summary>
        Friend ReadOnly Property str5000() As String
            Get
                Return ResourceManager.GetString("str5000", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Item Tag Validation.
        '''</summary>
        Friend ReadOnly Property str5001() As String
            Get
                Return ResourceManager.GetString("str5001", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Duplicate Tag Found.
        '''</summary>
        Friend ReadOnly Property str5002() As String
            Get
                Return ResourceManager.GetString("str5002", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to This action will result in a duplicate item tag for the instrument.
        '''        '''Action was canceled and instrument item tag was not changed..
        '''</summary>
        Friend ReadOnly Property str5003() As String
            Get
                Return ResourceManager.GetString("str5003", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &quot;Duplicate Item Tag Found, Do you want to create a duplicate Itemtag?&quot;.
        '''</summary>
        Friend ReadOnly Property str5004() As String
            Get
                Return ResourceManager.GetString("str5004", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &quot;Duplicate Item Tag found. The current value will be removed.&quot;.
        '''</summary>
        Friend ReadOnly Property str5005() As String
            Get
                Return ResourceManager.GetString("str5005", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Duplicate tag.
        '''</summary>
        Friend ReadOnly Property str5006() As String
            Get
                Return ResourceManager.GetString("str5006", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to found in active plant..
        '''</summary>
        Friend ReadOnly Property str5007() As String
            Get
                Return ResourceManager.GetString("str5007", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to found in AsBuilt plant..
        '''</summary>
        Friend ReadOnly Property str5008() As String
            Get
                Return ResourceManager.GetString("str5008", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Do you want the next available sequence number to be generated for you?.
        '''</summary>
        Friend ReadOnly Property str5009() As String
            Get
                Return ResourceManager.GetString("str5009", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to found in active project..
        '''</summary>
        Friend ReadOnly Property str5010() As String
            Get
                Return ResourceManager.GetString("str5010", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to found in AsBuilt plant or its projects..
        '''</summary>
        Friend ReadOnly Property str5011() As String
            Get
                Return ResourceManager.GetString("str5011", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
